name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

dependencies:
  cupertino_icons:
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv:
  flutter_lints:
  google_place:
    git:
      url: git@github.com:tmcmaster/google_place.git
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  google_place:
    path: ../